# The name of the workflow
name: CI Code testing 

# The events/triggers when it should be run
# Here we set that the workflow should run
# whenever there was a push or PR to the 
# main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  pull_request_target:
    branches: [main]  

# We define the jobs that should be run
# and the respective runner, ie virtual machine
# Here, the workflow runs on the latest ubuntu
jobs:
  code-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    # Below we define all steps that should be
    # run within the workflow
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.6'  

      # Step 3: Set conda
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
            activate-environment: anaconda-client-env
            environment-file: environment.yml
            auto-activate-base: false

      # Step 4: Install additional libraries with pip
      - name: Install libraries with pip
        run: |
          conda activate anaconda-client-env
          pip install -e .
      
      # Step 5: Run tests with pytest
      - name: Run tests with pytest
        run: |
              conda activate anaconda-client-env
              pytest audio_rep_networks/tests/